apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: aws-secrets
  namespace: {{ .Release.Namespace }}
spec:
  backendType: secretsManager
  data:
    - key: production/awssecrets/key
      name: AWS_ACCESS_KEY_ID
    - key: production/awssecrets/secret
      name: AWS_SECRET_ACCESS_KEY
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: gcs-secret
  namespace: {{ .Release.Namespace }}
spec:
  backendType: secretsManager
  data:
    - name: gcs_credential.json
      key: starship/gcpsecrets/prod/gcs_credential.json