---
apiVersion: v1
kind: ConfigMap
apiVersion: v1
metadata:
  name: starship-data-mappings
  namespace: "{{ .Release.Namespace }}"
data:
{{ (tpl (.Files.Glob ("conf/mapping/*") ).AsConfig . ) | indent 2 }}  
