apiVersion: v1
kind: Pod
metadata:
  name: nvidia-smi
spec:
  restartPolicy: OnFailure
  tolerations:
        - effect: NoSchedule
          key: role
          operator: Equal
          value: gpuworker
  nodeSelector:
        role: gpuworker     
  containers:
  - name: nvidia-smi
    image: nvidia/cuda:9.2-devel
    args:
    - "nvidia-smi"
    resources:
      limits:
        nvidia.com/gpu: 1