
apiVersion: batch/v1
kind: Job
metadata:
  name: ippandimfeature-table-creation
spec:
  template:
    spec:
      containers:
        - name: pinot-add-student-table-json
          image: apachepinot/pinot:latest
          command: ["/bin/bash", "-c", "--"]
          args:
          - |
            sleep 3600;
            # bin/pinot-ingestion-job.sh -jobSpecFile  /var/pinot/tables/ippanDimFeature_standalone_job_spec.yaml
          env:
            - name: JAVA_OPTS
              value: "-Xms4G -Xmx4G -Dpinot.admin.system.exit=true"
          volumeMounts:
            - name: tables
              mountPath: /var/pinot/tables
      restartPolicy: OnFailure
      volumes:
        - name: tables
          configMap:
            name: pinot-data-configuration
  backoffLimit: 100