---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: gcr-registry-key
  namespace: {{ .Release.Namespace }}
spec:
  backendType: secretsManager
  region: ap-northeast-1
  template:
    type: kubernetes.io/dockerconfigjson
  data:
    - name: .dockerconfigjson
      key: starship/dockercred/gcrauth.json