---
apiVersion: v1
kind: Service
metadata:
  name: cassandra-internal-lb
  namespace: {{ .Release.Namespace }}
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  labels:
    app: cassandracluster
spec:
  type: LoadBalancer
  ports:
  - name: cql
    port: 9042
    protocol: TCP
    targetPort: 9042
  selector:
    app: cassandracluster
    cassandracluster: cassandra
    cluster: starship-cassandra