apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: misc
spec:
  gateways:
    - gateway
  hosts:
    - "*"
  http:
    - match:
        - headers:
            user-agent:
              prefix: ELB-HealthChecker
          method:
            exact: GET
          uri:
            exact: /
      rewrite:
        authority: istio-ingressgateway.{{.Release.Namespace}}.svc.cluster.local:15021
        uri: /healthz/ready
      route:
        - destination:
            host: istio-ingressgateway.{{.Release.Namespace}}.svc.cluster.local
            port:
              number: 15021
              