pinot:
  image:
    tag: release-0.7.1
  cluster:
    name: pinot
  server:
    replicaCount: 2    
    nodeSelector:
      role: worker
      nodetype: c5.2xlarge
    tolerations:
    - key: role
      operator: Equal
      value: worker
      effect: NoSchedule 
    extra:
      configs: |-
        pinot.server.instance.enable.split.commit=true
        pinot.server.storage.factory.class.s3=org.apache.pinot.plugin.filesystem.S3PinotFS
        pinot.server.storage.factory.s3.region=ap-northeast-1
        pinot.server.segment.fetcher.protocols=file,http,s3
        pinot.server.segment.fetcher.s3.class=org.apache.pinot.common.utils.fetcher.PinotFSSegmentFetcher            
  controller:
    nodeSelector:
      role: worker
      nodetype: c5.2xlarge
    tolerations:
    - key: role
      operator: Equal
      value: worker
      effect: NoSchedule 
    # Extra configs will be appended to pinot-controller.conf file
    extra:
      configs: |-
        controller.data.dir=s3://unext-datascience/pinot-data/dev/controller-data
        controller.local.temp.dir=/var/pinot/controller/tmp-data/
        pinot.set.instance.id.to.hostname=true
        controller.task.scheduler.enabled=true
        controller.enable.split.commit=true
        pinot.controller.storage.factory.class.s3=org.apache.pinot.plugin.filesystem.S3PinotFS
        pinot.controller.storage.factory.s3.region=ap-northeast-1
        pinot.controller.segment.fetcher.protocols=file,http,s3
        pinot.controller.segment.fetcher.s3.class=org.apache.pinot.common.utils.fetcher.PinotFSSegmentFetcher

  broker:
    nodeSelector:
      role: worker
      nodetype: c5.2xlarge
    tolerations:
    - key: role
      operator: Equal
      value: worker
      effect: NoSchedule
  minion:
    nodeSelector:
      role: worker
      nodetype: c5.2xlarge
    tolerations:
    - key: role
      operator: Equal
      value: worker
      effect: NoSchedule
